[package]
name = "camenisch-lysyanskaya"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint-dig = {version = "0.8.1", features = ["rand"]}
rand = "0.8"